apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: nginx
spec:
  selector:
    app: nginx-label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: nginx-ssh
spec:
  selector:
    app: nginx-label
  ports:
    - name: https
      protocol: TCP
      port: 22
      targetPort: 22
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-label
  template:
    metadata:
      labels:
        app: nginx-label
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: my_nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 22
        - containerPort: 443
