apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - name: port-wordpress
      protocol: TCP
      port: 5050
      targetPort: 5050
      nodePort: 5050
  type: NodePort
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: wp-pvc
spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 6Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      restartPolicy: Always
      # les volumes à fournir au Pod (le champ .spec.volumes)
      #  et où les monter dans les conteneurs (le champ .spec.containers.volumeMounts).
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pvc
      containers:
      - name: wordpress
        image: my_wordpress
        imagePullPolicy: Never
        # The WORDPRESS_DB_HOST environment 
        # variable sets the name of the MySQL Service defined 
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          value : souad
        ports:
        - containerPort: 5050
          protocol: TCP
          name: wordpress
        volumeMounts:
        - mountPath: "/var/www/localhost/htdocs/wordpress"
          name: wordpress-persistent-storage
