# Telegraf is an agent for collecting metrics and writing them to InfluxDB 
# I should mount the docker socket from minikube into the container "telegraf"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      restartPolicy: Always
      containers:
        - image: my_telegraf
          name: telegraf
          imagePullPolicy: Never
          # The mount path is always the destination inside the Pod a volume gets mounted to.
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-config
              subPath: telegraf.conf
              readOnly: true
            #had socket for connection
            - mountPath: /var/run/docker.sock
              name: docker-socket
          envFrom:
            - secretRef:
                name: telegraf-secrets
      # A hostPath volume mounts a file or directory from the host node’s filesystem into my Pod
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: telegraf-config
          configMap:
            name: telegraf-config
# Check Data Injection Into InfluxDB
#  kubectl logs pod_influxdb