
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
spec:
  selector:
    app: ftps-label
  ports:
    - name: port-command
      protocol: TCP
      port: 21
      targetPort: 21
    - name: port-data
      protocol: TCP
      port: 20
      targetPort: 20
    - name: port1
      protocol: TCP
      port: 21000 
    - name: port2
      protocol: TCP
      port: 21001 
    - name: port3
      protocol: TCP
      port: 21002
    - name: port4
      protocol: TCP
      port: 21003 
    - name: port5
      protocol: TCP
      port: 21004 
    - name: port6
      protocol: TCP
      port: 21005 
    - name: port7
      protocol: TCP
      port: 21006 
    - name: port8
      protocol: TCP
      port: 21007 
    - name: port9
      protocol: TCP
      port: 21008
    - name: port10
      protocol: TCP
      port: 21009 
    - name: port11
      protocol: TCP
      port: 21010 
  type: LoadBalancer

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: total-volume
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: ftps-pvc
spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps-label
  template:
    metadata:
      labels:
        app: ftps-label
    spec:
      restartPolicy: Always
      volumes:
      - name: total-volume
        persistentVolumeClaim:
          claimName: ftps-pvc
      containers:
      - name: ftps
        image: my_ftps
        imagePullPolicy: Never
        ports:
          # port 21 for command channel
          # port 10090 for data channel
        - containerPort: 20
        - containerPort: 21
        - containerPort: 21000 
        - containerPort: 21001 
        - containerPort: 21002 
        - containerPort: 21003 
        - containerPort: 21004 
        - containerPort: 21005 
        - containerPort: 21006 
        - containerPort: 21007
        - containerPort: 21008 
        - containerPort: 21009 
        - containerPort: 21010 
          protocol: TCP
          name: "ftp-server"
        volumeMounts:
        - mountPath: "/home/ftpd"
          name: total-volume
        # env:
        # - name: FTP_USER
        #   value: "ftpd"
        # - name: FTP_PASS
        #   value: "1234"
        
